# This is meant to be run inside the Vagrant machine
CARTO_CONFIGURATION_FILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo '" This is a file autgenerated by setup_vagrant.sh' > .vimrc
cat ../../.vimrc | grep -v novagrant >> .vimrc

OVERRIDABLE_FILES=('.vimrc' '.tmuxinator/cartodb.yml')

for overridable_file in "${OVERRIDABLE_FILES[@]}"; do
  overridable_file_full_path="$HOME/$overridable_file"
  if [ -f $overridable_file_full_path ] && [ ! -h $overridable_file_full_path ]; then
    echo "Creating backup of $overridable_file_full_path"
    mv $overridable_file_full_path $overridable_file_full_path.bak
  fi

  ln -sf $CARTO_CONFIGURATION_FILES_DIR/$overridable_file $overridable_file_full_path
done
